module.exports = {
  sm: ["14px", { lineHeight: "normal" }],
  lg: ["18px", { lineHeight: "21.6px" }],
  xl: ["20px", { lineHeight: "normal" }],
  "2xl": ["24px", { lineHeight: "normal" }],
  "display-sm": ["96px", { lineHeight: "100%" }],
  "heading-xs": ["24px", { lineHeight: "32px" }],
  "heading-sm": ["30px", { lineHeight: "38px" }],
  "heading-md": ["36px", { lineHeight: "44px" }],
  "heading-lg": ["48px", { lineHeight: "56px" }],
  "heading-xl": ["60px", { lineHeight: "68px" }],
  "heading-2xl": ["72px", { lineHeight: "80px" }],
  "label-xs": ["10px", { lineHeight: "normal" }],
  "label-sm": ["12px", { lineHeight: "normal" }],
  "label-md": ["14px", { lineHeight: "normal" }],
  "label-lg": ["16px", { lineHeight: "normal" }],
  "paragraph-lg": ["18px", { lineHeight: "160%" }],
  "paragraph-xl": ["20px", { lineHeight: "160%" }],
};
